/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Location;
import pfe.UtilConnexion;

/**
 *
 * @author saad
 */
public class AjouterLoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterGrp
     */
    Connection con;

    public AjouterLoc() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtlville = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtcodeposta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnajouterGRP = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(616, 277));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 117, 128));
        jLabel1.setText("Formulaire d'ajout d'un Location");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 570, 35));

        txtadresse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtadresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadresseActionPerformed(evt);
            }
        });
        getContentPane().add(txtadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 236, -1));

        jLabel2.setText("Adresse de rue:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        txtlville.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtlville, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 236, -1));

        jLabel13.setText("ville:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, -1, -1));

        txtcodeposta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtcodeposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 236, -1));

        jLabel14.setText("code de postal:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, -1, -1));

        btnajouterGRP.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnajouterGRP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-adresse-28.png"))); // NOI18N
        btnajouterGRP.setText("Ajouter la location");
        btnajouterGRP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnajouterGRP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterGRPActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouterGRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 230, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtadresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadresseActionPerformed

    private void btnajouterGRPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterGRPActionPerformed

        try {
            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment ajouter cette location?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                String req = "insert into location values (seq_loc.nextval,?,?,?)";
                PreparedStatement ps = con.prepareStatement(req);
                ps.setString(1, txtadresse.getText());
                ps.setString(2, txtlville.getText());
                ps.setString(3, txtcodeposta.getText());
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null, "La location ajouté avec succée!");
                txtadresse.setText("");
                txtlville.setText("");
                txtcodeposta.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(AjouterLoc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnajouterGRPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouterGRP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtcodeposta;
    private javax.swing.JTextField txtlville;
    // End of variables declaration//GEN-END:variables
}
