/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Location;
//import oracle.net.nt.ConnOption;
import pfe.UtilConnexion;

/**
 *
 * @author saad
 */
public class AjouterEmp extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterEns
     */
    Connection con;
    public AjouterEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtadresse = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txttel = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtrem = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtvers = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnajouterens = new javax.swing.JButton();
        txtlangue = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(579, 392));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 117, 128));
        jLabel4.setText("Formulaire d'ajout d'un employee");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 236, -1));

        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 236, -1));

        jLabel13.setText("Prènom:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        txtadresse.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtadresse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 236, 20));

        jLabel19.setText("Adresse:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        txttel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 236, -1));

        jLabel20.setText("Téléphone:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, -1, -1));

        txtrem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 236, -1));

        jLabel21.setText("salaire:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 320, -1, -1));

        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 236, 20));

        jLabel22.setText("Email");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        txtvers.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtvers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtvers, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 236, 20));

        jLabel24.setText("rib:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        btnajouterens.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnajouterens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_24px.png"))); // NOI18N
        btnajouterens.setText("Ajouter l'enseignant");
        btnajouterens.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnajouterens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterensActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouterens, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 230, -1));

        txtlangue.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtlangue, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 236, -1));

        jLabel23.setText("dapartement:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/s.jpg"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(1370, 700));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void btnajouterensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterensActionPerformed
try {
            if(JOptionPane.showConfirmDialog(null, "Voulez vraiment ajouter cet Employee?")==JOptionPane.YES_OPTION){
          
          
            con= UtilConnexion.seConnecter();
             String req="insert into employee values (seq_emp.nextval,?,?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(req);
                
            ps.setString(1, txtnom.getText());
            ps.setString(2, txtprenom.getText());
            ps.setString(3, txtadresse.getText());
            ps.setString(4, txttel.getText());
            ps.setString(5, txtemail.getText());
            ps.setString(6, txtlangue.getText());
            ps.setInt(7,Integer.parseInt( txtrem.getText()));
            ps.setInt(8, Integer.parseInt(txtvers.getText()));
            
            ps.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "L'employee ajouté avec succée!!");
            txtnom.setText("");
            txtprenom.setText("");
            txtadresse.setText("");
            txttel.setText("");
            txtemail.setText("");
            txtlangue.setText("");
            txtrem.setText("");
            txtvers.setText("");
           
           }
           
           
            
            
            
        } catch (Exception ex) {
            Logger.getLogger(AjouterEmp.class.getName()).log(Level.SEVERE, null, ex);
        }        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnajouterensActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouterens;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtlangue;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrem;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtvers;
    // End of variables declaration//GEN-END:variables
}
