/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pfe.UtilConnexion;

/**
 *
 * @author saad
 */
public class AjouterUtil extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterUtil
     */
    
    Connection con;
    
    public AjouterUtil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        txtlogin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtmdp = new javax.swing.JTextField();
        cbrole = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        btnajouterutil = new javax.swing.JButton();
        cbQust = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtrepons = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(580, 339));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 117, 128));
        jLabel1.setText("Formulaire d'ajout d'un utilisateur");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 610, 35));

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, -1));

        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 250, -1));

        jLabel13.setText("Prènom:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, -1, -1));

        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, 260, -1));

        txtlogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 260, 20));

        jLabel19.setText("username:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel20.setText("Le mot de passe:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 230, -1, -1));

        txtmdp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 260, -1));

        cbrole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Gerant", "User" }));
        cbrole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbrole.setOpaque(false);
        cbrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbroleActionPerformed(evt);
            }
        });
        getContentPane().add(cbrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 260, -1));

        jLabel16.setText("Son role:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 160, -1));

        btnajouterutil.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnajouterutil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_24px.png"))); // NOI18N
        btnajouterutil.setText("Ajouter l'utilisateur");
        btnajouterutil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnajouterutil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouterutilActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouterutil, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, 240, -1));

        cbQust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quel a été votre premier animal de compagnie?", "D'où venez-vous?", "Quel est ton surnom?", "Le nom de votre animal de compagnie?", "Nom de votre meilleur ami?" }));
        cbQust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbQust.setOpaque(false);
        cbQust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQustActionPerformed(evt);
            }
        });
        getContentPane().add(cbQust, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 260, -1));

        jLabel17.setText("Question:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 160, -1));

        jLabel21.setText("Reponse:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, -1, -1));

        txtrepons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtrepons, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 260, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void cbroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbroleActionPerformed

    private void btnajouterutilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouterutilActionPerformed
try {
            if(JOptionPane.showConfirmDialog(null, "Voulez vraiment ajouter cet Utilisateur?")==JOptionPane.YES_OPTION){
          
           String role= (String) cbrole.getSelectedItem();
           String quest= (String) cbQust.getSelectedItem();
          
              
                    con= UtilConnexion.seConnecter();
                
             String req="insert into compte values (seq_compte.nextval,?,?,?,?,?,?,?)";
                PreparedStatement ps=con.prepareStatement(req);
                
            ps.setString(1, txtnom.getText());
            ps.setString(2, txtprenom.getText());
            ps.setString(3, txtlogin.getText());
            ps.setString(4,txtmdp.getText());
            ps.setString(5, role);
            ps.setString(6, quest);
            ps.setString(7, txtrepons.getText());
           
            
            ps.executeUpdate();
            con.close();
            JOptionPane.showMessageDialog(null, "L'Utilisateur ajouté avec succée!!");
            txtnom.setText("");
            txtprenom.setText("");
            txtlogin.setText("");
            txtmdp.setText("");
            txtrepons.setText("");
            
           
           }}
                catch (Exception ex) {
                    Logger.getLogger(AjouterLoc.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btnajouterutilActionPerformed

    private void cbQustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQustActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouterutil;
    private javax.swing.JComboBox cbQust;
    private javax.swing.JComboBox cbrole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrepons;
    // End of variables declaration//GEN-END:variables
}
