/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Client;
import models.Location;
import pfe.UtilConnexion;

/**
 *
 * @author saad
 */
public class AjouterClt extends javax.swing.JInternalFrame {

    /**
     * Creates new form AjouterEtud
     */
    Connection con;
    PreparedStatement ps;
    ArrayList<Client> le = new ArrayList<Client>();

    public AjouterClt() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbg = new javax.swing.JComboBox();
        txtprenom = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtdaterend = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtsalaire = new javax.swing.JTextField();
        txtvers = new javax.swing.JTextField();
        btnajouteretud = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(592, 504));
        setPreferredSize(new java.awt.Dimension(1370, 700));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Prènom:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        cbg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(cbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 240, -1));

        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 236, -1));

        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        getContentPane().add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 236, -1));

        txtdaterend.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtdaterend, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 236, -1));

        txtemail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtemail.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, 236, -1));

        txttel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txttel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 236, -1));

        txtsalaire.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsalaire.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtsalaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 236, -1));

        txtvers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        getContentPane().add(txtvers, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 240, -1));

        btnajouteretud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnajouteretud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_24px.png"))); // NOI18N
        btnajouteretud.setText("Ajouter Client");
        btnajouteretud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnajouteretud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouteretudActionPerformed(evt);
            }
        });
        getContentPane().add(btnajouteretud, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 220, -1));

        jLabel23.setText("Versement:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, 150, -1));

        jLabel21.setText("prix de srvice:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, -1));

        jLabel18.setText("Location:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, -1, -1));

        jLabel20.setText("Téléphone:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        jLabel17.setText("Email");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jLabel14.setText("Date De rendez vous:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 33)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 117, 128));
        jLabel4.setText("Formulaire d'ajout d'un Client");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jLabel1.setText("dd/mm/yyyy");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnajouteretudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouteretudActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment ajouter cet Client?") == JOptionPane.YES_OPTION) {
                Location grp = (Location) cbg.getSelectedItem();
                con = UtilConnexion.seConnecter();
                String req = "insert into client values (seq_clt.nextval,?,?,?,?,?,?,?,?)";
                PreparedStatement ps = con.prepareStatement(req);
                ps.setString(1, txtnom.getText());
                ps.setString(2, txtprenom.getText());
                java.util.Date d = new SimpleDateFormat("dd/MM/yyyy").parse(txtdaterend.getText());
                ps.setDate(3, java.sql.Date.valueOf(new SimpleDateFormat("yyyy-MM-dd").format(d)));
                ps.setString(4, txtemail.getText());
                ps.setString(5, txttel.getText());
                ps.setString(6, txtsalaire.getText());
                ps.setString(7, txtvers.getText());
                ps.setInt(8, grp.getId_loc());
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null, "Client ajouté avec succée!!");
                txtnom.setText("");
                txtprenom.setText("");
                txtdaterend.setText("");
                txtemail.setText("");
                txttel.setText("");
                txtsalaire.setText("");
                txtvers.setText("");
            }

        } catch (Exception ex) {
            Logger.getLogger(AjouterClt.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnajouteretudActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        try {
            // TODO add your handling code here:
            Connection con = UtilConnexion.seConnecter();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from location");
            while (rs.next()) {
                cbg.addItem(new Location(rs.getInt(1), rs.getString(2), rs.getString(3), rs.getInt(4)));
            }
            rs.close();
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(AjouterClt.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formInternalFrameOpened

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajouteretud;
    private javax.swing.JComboBox cbg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtdaterend;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtsalaire;
    private javax.swing.JTextField txttel;
    private javax.swing.JTextField txtvers;
    // End of variables declaration//GEN-END:variables

}
