/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import models.Employee;
import models.Client;
import models.Location;
import pfe.UtilConnexion;

/**
 *
 * @author mehdierror404
 */
public class ModifierLoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModifierGrp
     */
    Connection con;

    int pos = 0;
    ArrayList<Location> lg = new ArrayList<Location>();

    public ModifierLoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnmodifieretud = new javax.swing.JButton();
        txtadresse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtcodeposta = new javax.swing.JTextField();
        txtlville = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnpremier = new javax.swing.JButton();
        btnpre = new javax.swing.JButton();
        btnsuiv = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(678, 430));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(120, 196, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selectionner un location pour modifier");

        combo.setForeground(new java.awt.Color(204, 204, 255));
        combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(418, 418, 418)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(120, 196, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmodifieretud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnmodifieretud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_24px.png"))); // NOI18N
        btnmodifieretud.setText("Modifier cette location");
        btnmodifieretud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodifieretud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifieretudActionPerformed(evt);
            }
        });
        jPanel2.add(btnmodifieretud, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 260, -1));

        txtadresse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtadresse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadresseActionPerformed(evt);
            }
        });
        jPanel2.add(txtadresse, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 236, -1));

        jLabel2.setText("Adresse de rue:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        jLabel14.setText("code de postal:");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        txtcodeposta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtcodeposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 236, -1));

        txtlville.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtlville, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 236, -1));

        jLabel13.setText("ville:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, -1, -1));

        btnpremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_to_start_26px.png"))); // NOI18N
        btnpremier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });
        jPanel2.add(btnpremier, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 80, -1));

        btnpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_26px.png"))); // NOI18N
        btnpre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreActionPerformed(evt);
            }
        });
        jPanel2.add(btnpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, 80, -1));

        btnsuiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_next_page_26px.png"))); // NOI18N
        btnsuiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivActionPerformed(evt);
            }
        });
        jPanel2.add(btnsuiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 80, -1));

        btndernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_end_26px.png"))); // NOI18N
        btndernier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });
        jPanel2.add(btndernier, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifieretudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifieretudActionPerformed
        // TODO add your handling code here:
        try {
            Location g = lg.get(pos);
            g.setRue_Adresse(txtadresse.getText());
            g.setVille(txtlville.getText());
            g.setCode_postal(Integer.parseInt(txtcodeposta.getText()));
            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment modifier cette location?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                PreparedStatement ps = con.prepareStatement("update location set RUE_ADRESSE=?,VILLE=?,CODE_POSTAL=? where id_loc=?");
                ps.setString(1, g.getRue_Adresse());
                ps.setString(2, g.getVille());
                ps.setInt(3, g.getCode_postal());
                ps.setInt(4, g.getId_loc());

                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null, "Location modifié avec succée!!");

            }
        } catch (Exception ex) {
            Logger.getLogger(ModifierLoc.class.getName()).log(Level.SEVERE, null, ex.getMessage());
        }

    }//GEN-LAST:event_btnmodifieretudActionPerformed

    private void txtadresseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadresseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadresseActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con= UtilConnexion.seConnecter();
            Statement s=con.createStatement();
            
            ResultSet r=s.executeQuery("select * from location");
            while(r.next()){
               
                combo.addItem(new Location(r.getInt("ID_LOC"),
              r.getString("RUE_ADRESSE"),r.getString("VILLE"),r.getInt("CODE_POSTAL")));
            }
            s.close();
            r.close();
            
            
            Statement st2=con.createStatement();
            ResultSet rs2=st2.executeQuery("select * from location");
            while(rs2.next()){
            lg.add(new Location(rs2.getInt("ID_LOC"),
              rs2.getString("RUE_ADRESSE"),rs2.getString("VILLE"),rs2.getInt("CODE_POSTAL")));
            }
            Afficher();
            st2.close();
            rs2.close();
            con.close();
            
        } catch (Exception ex) {
            Logger.getLogger(ModifierLoc.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formInternalFrameOpened

    private void btnsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivActionPerformed
        // TODO add your handling code here:
        try {
            pos++;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos--;
            JOptionPane.showMessageDialog(rootPane, "Le dernier");
            Afficher();
        }
    }//GEN-LAST:event_btnsuivActionPerformed

    private void btnpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreActionPerformed
        // TODO add your handling code here:
        try {
            pos--;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos++;
            JOptionPane.showMessageDialog(rootPane, "Le premier");
            Afficher();
        }
    }//GEN-LAST:event_btnpreActionPerformed

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        pos = 0;
        Afficher();
    }//GEN-LAST:event_btnpremierActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        try{
            Location g=  (Location) combo.getSelectedItem();
            txtadresse.setText(g.getRue_Adresse());
        txtlville.setText(g.getVille());
        txtcodeposta.setText(g.getCode_postal()+"");

        } catch (Exception ex) {
            Logger.getLogger(ModifierLoc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboItemStateChanged

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
        pos = lg.size() - 1;
        Afficher();
    }//GEN-LAST:event_btndernierActionPerformed
    private void Afficher() {
        Location g= lg.get(pos);
        txtadresse.setText(g.getRue_Adresse());
        txtlville.setText(g.getVille());
        txtcodeposta.setText(g.getCode_postal()+"");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnmodifieretud;
    private javax.swing.JButton btnpre;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuiv;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtcodeposta;
    private javax.swing.JTextField txtlville;
    // End of variables declaration//GEN-END:variables
}
