/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import models.Compte;
import pfe.UtilConnexion;

/**
 *
 * @author mehdierror404
 */
public class ModifierUtil extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModifierUtil
     */
    Connection con;

    int pos = 0;
    ArrayList<Compte> lu = new ArrayList<Compte>();

    public ModifierUtil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        btnmodifieretud = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtmdp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbrole = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        btnpremier = new javax.swing.JButton();
        btnpre = new javax.swing.JButton();
        btnsuiv = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();
        cbQust = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtrepons = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(635, 487));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(120, 196, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selectionner un utilisateur pour modifier");

        combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(462, 462, 462)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(120, 196, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmodifieretud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnmodifieretud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_24px.png"))); // NOI18N
        btnmodifieretud.setText("Modifier cet utilisateur");
        btnmodifieretud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodifieretud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifieretudActionPerformed(evt);
            }
        });
        jPanel2.add(btnmodifieretud, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        txtnom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });
        jPanel2.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 236, -1));

        jLabel2.setText("Nom:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        txtprenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 236, -1));

        jLabel13.setText("Prènom:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        txtlogin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtlogin.setEnabled(false);
        jPanel2.add(txtlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 236, 20));

        jLabel19.setText("Login de l'utilisateur:");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        txtmdp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmdp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtmdp.setEnabled(false);
        jPanel2.add(txtmdp, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 236, -1));

        jLabel20.setText("Le mot de passe:");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        cbrole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Gerant", "User" }));
        cbrole.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbrole.setOpaque(false);
        cbrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbroleActionPerformed(evt);
            }
        });
        jPanel2.add(cbrole, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 240, -1));

        jLabel16.setText("Son role:");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 160, -1));

        btnpremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_to_start_26px.png"))); // NOI18N
        btnpremier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });
        jPanel2.add(btnpremier, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 80, -1));

        btnpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_26px.png"))); // NOI18N
        btnpre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreActionPerformed(evt);
            }
        });
        jPanel2.add(btnpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, 80, -1));

        btnsuiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_next_page_26px.png"))); // NOI18N
        btnsuiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivActionPerformed(evt);
            }
        });
        jPanel2.add(btnsuiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 80, -1));

        btndernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_end_26px.png"))); // NOI18N
        btndernier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });
        jPanel2.add(btndernier, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 290, 80, -1));

        cbQust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quel a été votre premier animal de compagnie?", "D'où venez-vous?", "Quel est ton surnom?", "Le nom de votre animal de compagnie?", "Nom de votre meilleur ami?" }));
        cbQust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbQust.setOpaque(false);
        cbQust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQustActionPerformed(evt);
            }
        });
        jPanel2.add(cbQust, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 260, -1));

        jLabel17.setText("Question:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 160, -1));

        jLabel21.setText("Reponse:");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, -1, -1));

        txtrepons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.add(txtrepons, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 236, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1354, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifieretudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifieretudActionPerformed
        // TODO add your handling code here:
        try {
            Compte u = lu.get(pos);
            u.setNom(txtnom.getText());
            u.setPrenom(txtprenom.getText());
            u.setUser(txtlogin.getText());
            u.setPassword(txtmdp.getText());
            u.setQUESTION((String) cbQust.getSelectedItem());
            u.setANSWER(txtrepons.getText());
            u.setRole((String) cbrole.getSelectedItem());

            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment modifier cet utilisateur?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                PreparedStatement ps = con.prepareStatement("update compte set nom=?,prenom=?,username=?,password=?,role=?,QUESTION=?,ANSWER=? where iduser=?");
                String role = (String) cbrole.getSelectedItem();
                String quest = (String) cbQust.getSelectedItem();
                ps.setString(1, u.getNom());
                ps.setString(2, u.getPrenom());
                ps.setString(3, u.getUser());
                ps.setString(4, u.getPassword());
                ps.setString(5, role);
                ps.setString(6, quest);
                ps.setString(7, u.getANSWER());
                ps.setInt(8, u.getIduser());
                ps.executeUpdate();
                con.close();
                JOptionPane.showMessageDialog(null, "L'utilisateur modifié avec succée!!");

            }
        } catch (Exception ex) {
            Logger.getLogger(ModifierUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmodifieretudActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomActionPerformed

    private void cbroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbroleActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        try {
            Compte u = (Compte) combo.getSelectedItem();
            txtnom.setText(u.getNom());
            txtprenom.setText(u.getPrenom());
            txtlogin.setText(u.getUser());
            txtmdp.setText(u.getPassword());
            cbrole.setSelectedItem(u.getRole());
            cbQust.setSelectedItem(u.getQUESTION());
            txtrepons.setText(u.getANSWER());
        } catch (Exception ex) {
            Logger.getLogger(ModifierUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboItemStateChanged

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = UtilConnexion.seConnecter();
            Statement s = con.createStatement();

            ResultSet r = s.executeQuery("select * from compte");
            while (r.next()) {

                combo.addItem(new Compte(r.getInt("iduser"), r.getString("nom"), r.getString("prenom"),
                        r.getString("username"), r.getString("password"), r.getString("role"),r.getString("QUESTION"),r.getString("ANSWER")));
            }
            s.close();
            r.close();

            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from compte");
            while (rs2.next()) {
                lu.add(new Compte(rs2.getInt("iduser"), rs2.getString("nom"), rs2.getString("prenom"),
                        rs2.getString("username"), rs2.getString("password"), rs2.getString("role"),rs2.getString("QUESTION"),rs2.getString("ANSWER")));
            }
            Afficher();
            st2.close();
            rs2.close();
            con.close();

        } catch (Exception ex) {
           Logger.getLogger(ModifierUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbQustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQustActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
        pos = lu.size() - 1;
        Afficher();
    }//GEN-LAST:event_btndernierActionPerformed

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        pos = 0;
        Afficher();
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreActionPerformed
        // TODO add your handling code here:
        try {
            pos--;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos++;
            JOptionPane.showMessageDialog(rootPane, "Le premier");
            Afficher();
        }
    }//GEN-LAST:event_btnpreActionPerformed

    private void btnsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivActionPerformed
        // TODO add your handling code here:
         try {
            pos++;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos--;
            JOptionPane.showMessageDialog(rootPane, "Le dernier");
            Afficher();
        }
    }//GEN-LAST:event_btnsuivActionPerformed

    private void Afficher() {
        Compte u = lu.get(pos);
        txtnom.setText(u.getNom());
        txtprenom.setText(u.getPrenom());
        txtlogin.setText(u.getUser());
        txtmdp.setText(u.getPassword());
        cbrole.setSelectedItem(u.getRole());
        cbQust.setSelectedItem(u.getQUESTION());
        txtrepons.setText(u.getANSWER());

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnmodifieretud;
    private javax.swing.JButton btnpre;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuiv;
    private javax.swing.JComboBox cbQust;
    private javax.swing.JComboBox cbrole;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrepons;
    // End of variables declaration//GEN-END:variables
}
