/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Compte;
import pfe.UtilConnexion;

/**
 *
 * @author mehdierror404
 */
public class SupprimerUtil extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupprimerUtil
     */
    Connection con;

    int pos = 0;
    ArrayList<Compte> lu = new ArrayList<Compte>();

    public SupprimerUtil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtprenom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnmodifieretud = new javax.swing.JButton();
        txtnom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtlogin = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cbrole = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        txtmdp = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnpremier = new javax.swing.JButton();
        btnpre = new javax.swing.JButton();
        btnsuiv = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();
        cbQust = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        txtrepons = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(619, 512));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(120, 196, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Selectionner un utilisateur pour Supprimer");

        combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(501, 501, 501)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jPanel2.setBackground(new java.awt.Color(120, 196, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtprenom.setEnabled(false);

        jLabel2.setText("Prénom:");

        btnmodifieretud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnmodifieretud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_24px_1.png"))); // NOI18N
        btnmodifieretud.setText("Supprimer cet utilisateur");
        btnmodifieretud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodifieretud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifieretudActionPerformed(evt);
            }
        });

        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.setEnabled(false);

        jLabel3.setText("Nom:");

        txtlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtlogin.setEnabled(false);

        jLabel14.setText("Login:");

        cbrole.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrateur", "Gerant", "AgentDaccueil" }));
        cbrole.setEnabled(false);
        cbrole.setOpaque(false);
        cbrole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbroleActionPerformed(evt);
            }
        });

        jLabel16.setText("Son role:");

        txtmdp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtmdp.setEnabled(false);

        jLabel20.setText("Le mot de passe:");

        btnpremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_to_start_26px.png"))); // NOI18N
        btnpremier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });

        btnpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_26px.png"))); // NOI18N
        btnpre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreActionPerformed(evt);
            }
        });

        btnsuiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_next_page_26px.png"))); // NOI18N
        btnsuiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivActionPerformed(evt);
            }
        });

        btndernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_end_26px.png"))); // NOI18N
        btndernier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });

        cbQust.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Quel a été votre premier animal de compagnie?", "D'où venez-vous?", "Quel est ton surnom?", "Le nom de votre animal de compagnie?", "Nom de votre meilleur ami?" }));
        cbQust.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbQust.setOpaque(false);
        cbQust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQustActionPerformed(evt);
            }
        });

        jLabel17.setText("Question:");

        txtrepons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel21.setText("Reponse:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbrole, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtlogin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel14)))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(jLabel21))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cbQust, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(txtrepons, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(521, 521, 521)
                        .addComponent(btnmodifieretud)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(btnpremier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(btnpre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btndernier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(466, 466, 466))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel20))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel21))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbQust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrepons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(3, 3, 3)
                .addComponent(cbrole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpremier)
                    .addComponent(btnpre)
                    .addComponent(btnsuiv)
                    .addComponent(btndernier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnmodifieretud)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifieretudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifieretudActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment Supprimer cet utilisateur?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                PreparedStatement ps = con.prepareStatement("delete from compte where username=?");
                ps.setString(1, txtlogin.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "L'utilisateur supprimé avec succeé!!");
            }
        } catch (Exception ex) {
            Logger.getLogger(SupprimerUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmodifieretudActionPerformed

    private void cbroleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbroleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbroleActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        try {
            Compte u = (Compte) combo.getSelectedItem();
            txtprenom.setText(u.getNom());
            txtprenom.setText(u.getPrenom());
            txtlogin.setText(u.getUser());
            txtmdp.setText(u.getPassword());
            cbrole.setSelectedItem(u.getRole());
            cbQust.setSelectedItem(u.getQUESTION());
            txtrepons.setText(u.getANSWER());
        } catch (Exception ex) {
            Logger.getLogger(SupprimerUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboItemStateChanged

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        pos = 0;
        Afficher();
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreActionPerformed
        // TODO add your handling code here:
       try {
            pos--;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos++;
            JOptionPane.showMessageDialog(rootPane, "Le premier");
            Afficher();
        }
    }//GEN-LAST:event_btnpreActionPerformed

    private void btnsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivActionPerformed
        // TODO add your handling code here:
       try {
            pos++;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos--;
            JOptionPane.showMessageDialog(rootPane, "Le dernier");
            Afficher();
        }
    }//GEN-LAST:event_btnsuivActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
        pos = lu.size() - 1;
        Afficher();
    }//GEN-LAST:event_btndernierActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = UtilConnexion.seConnecter();
            Statement s = con.createStatement();

            ResultSet r = s.executeQuery("select * from compte");
            while (r.next()) {

                combo.addItem(new Compte(r.getInt("iduser"), r.getString("nom"), r.getString("prenom"),
                        r.getString("username"), r.getString("password"), r.getString("role"), r.getString("QUESTION"), r.getString("ANSWER")));
            }
            s.close();
            r.close();

            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from compte");
            while (rs2.next()) {
                lu.add(new Compte(rs2.getInt("iduser"), rs2.getString("nom"), rs2.getString("prenom"),
                        rs2.getString("username"), rs2.getString("password"), rs2.getString("role"), rs2.getString("QUESTION"), rs2.getString("ANSWER")));
            }
            Afficher();
            st2.close();
            rs2.close();
            con.close();

        } catch (Exception ex) {
            Logger.getLogger(ModifierUtil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void cbQustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbQustActionPerformed
    private void Afficher() {
        Compte u = lu.get(pos);
        txtnom.setText(u.getNom());
        txtprenom.setText(u.getPrenom());
        txtlogin.setText(u.getUser());
        txtmdp.setText(u.getPassword());
        cbrole.setSelectedItem(u.getRole());
        cbQust.setSelectedItem(u.getQUESTION());
        txtrepons.setText(u.getANSWER());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnmodifieretud;
    private javax.swing.JButton btnpre;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuiv;
    private javax.swing.JComboBox cbQust;
    private javax.swing.JComboBox cbrole;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtlogin;
    private javax.swing.JTextField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrepons;
    // End of variables declaration//GEN-END:variables
}
