/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Location;
import pfe.UtilConnexion;

/**
 *
 * @author mehdierror404
 */
public class SupprimerLoc extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupprimerGrp
     */
    Connection con;

    int pos = 0;
    ArrayList<Location> lg = new ArrayList<Location>();

    public SupprimerLoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtlville = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnmodifieretud = new javax.swing.JButton();
        txtadresse = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcodeposta = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btndernier = new javax.swing.JButton();
        btnsuiv = new javax.swing.JButton();
        btnpre = new javax.swing.JButton();
        btnpremier = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(620, 487));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(120, 196, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Selectionner une location pour Supprimer");

        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(317, 317, 317))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(120, 196, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtlville.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtlville.setEnabled(false);

        jLabel2.setText("ville:");

        btnmodifieretud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnmodifieretud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_24px_1.png"))); // NOI18N
        btnmodifieretud.setText("Supprimer ce groupe");
        btnmodifieretud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifieretudActionPerformed(evt);
            }
        });

        txtadresse.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtadresse.setEnabled(false);

        jLabel3.setText("Adresse de rue:");

        txtcodeposta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtcodeposta.setEnabled(false);

        jLabel14.setText("code de postal:");

        btndernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_end_26px.png"))); // NOI18N
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });

        btnsuiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_next_page_26px.png"))); // NOI18N
        btnsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivActionPerformed(evt);
            }
        });

        btnpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_26px.png"))); // NOI18N
        btnpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreActionPerformed(evt);
            }
        });

        btnpremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_to_start_26px.png"))); // NOI18N
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(371, 371, 371)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtcodeposta, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtlville, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnpremier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnpre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btndernier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(btnmodifieretud)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(txtadresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(txtlville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(6, 6, 6)
                .addComponent(txtcodeposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpremier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndernier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnmodifieretud)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifieretudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifieretudActionPerformed
        // TODO add your handling code here:
        try {
            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment Supprimer cette location?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                PreparedStatement ps = con.prepareStatement("delete from location where VILLE=?");
                ps.setString(1, txtlville.getText());
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "La location supprimé avec succeé!!");
            }
        } catch (Exception ex) {
            Logger.getLogger(SupprimerLoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmodifieretudActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        try {
            Location g = (Location) combo.getSelectedItem();
            txtadresse.setText(g.getRue_Adresse());
            txtlville.setText(g.getVille());
            txtcodeposta.setText(g.getCode_postal()+ "");

        } catch (Exception ex) {
            Logger.getLogger(SupprimerLoc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboItemStateChanged

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        pos = 0;
        Afficher();
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreActionPerformed
        // TODO add your handling code here:
       try {
            pos--;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos++;
            JOptionPane.showMessageDialog(rootPane, "Le premier");
            Afficher();
        }
    }//GEN-LAST:event_btnpreActionPerformed

    private void btnsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivActionPerformed
        // TODO add your handling code here:
        try {
            pos++;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos--;
            JOptionPane.showMessageDialog(rootPane, "Le dernier");
            Afficher();
        }
    }//GEN-LAST:event_btnsuivActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
        pos = lg.size() - 1;
        Afficher();
    }//GEN-LAST:event_btndernierActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = UtilConnexion.seConnecter();
            Statement s = con.createStatement();

            ResultSet r = s.executeQuery("select * from location");
            while (r.next()) {

                combo.addItem(new Location(r.getInt("ID_LOC"),
                        r.getString("RUE_ADRESSE"), r.getString("VILLE"), r.getInt("CODE_POSTAL")));
            }
            s.close();
            r.close();

            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from location");
            while (rs2.next()) {
                lg.add(new Location(rs2.getInt("ID_LOC"),
                        rs2.getString("RUE_ADRESSE"), rs2.getString("VILLE"), rs2.getInt("CODE_POSTAL")));
            }
            Afficher();
            st2.close();
            rs2.close();
            con.close();
        } catch (Exception ex) {
            Logger.getLogger(SupprimerLoc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formInternalFrameOpened
    private void Afficher() {
        Location g = lg.get(pos);
        txtadresse.setText(g.getRue_Adresse());
        txtlville.setText(g.getVille());
        txtcodeposta.setText(g.getCode_postal() + "");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnmodifieretud;
    private javax.swing.JButton btnpre;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuiv;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtadresse;
    private javax.swing.JTextField txtcodeposta;
    private javax.swing.JTextField txtlville;
    // End of variables declaration//GEN-END:variables
}
