/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Employee;
import models.Client;
import models.Location;
import pfe.UtilConnexion;

/**
 *
 * @author mehdierror404
 */
public class SupprimerEmp extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupprimerEns
     */
    int pos = 0;
    Connection con;
    ArrayList<Employee> le = new ArrayList<Employee>();

    public SupprimerEmp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        btnmodifieretud = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnpremier = new javax.swing.JButton();
        btnpre = new javax.swing.JButton();
        btnsuiv = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(620, 492));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(120, 196, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Selectionner un Employee pour supprimer");

        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel1)))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1350, 210));

        jPanel2.setBackground(new java.awt.Color(120, 196, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.setEnabled(false);

        jLabel2.setText("Nom:");

        jLabel13.setText("Prènom:");

        txtprenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtprenom.setEnabled(false);

        btnmodifieretud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnmodifieretud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_24px_1.png"))); // NOI18N
        btnmodifieretud.setText("Supprimer cet Employee ");
        btnmodifieretud.setActionCommand("Supprimer cet Employee\n");
        btnmodifieretud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifieretudActionPerformed(evt);
            }
        });

        txtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtid.setEnabled(false);

        jLabel3.setText("ID-Empoyee:");

        btnpremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_to_start_26px.png"))); // NOI18N
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });

        btnpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_26px.png"))); // NOI18N
        btnpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreActionPerformed(evt);
            }
        });

        btnsuiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_next_page_26px.png"))); // NOI18N
        btnsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivActionPerformed(evt);
            }
        });

        btndernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_end_26px.png"))); // NOI18N
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(371, 371, 371)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(255, 255, 255)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnmodifieretud)
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnpremier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnpre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btndernier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(459, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpremier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndernier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnmodifieretud)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 1350, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmodifieretudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifieretudActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:

            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment Supprimer cet Employee?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                PreparedStatement ps = con.prepareStatement("delete from employee where idemp=?");
                ps.setInt(1, Integer.parseInt(txtid.getText()));
                ps.executeUpdate();
                le.remove(pos);
                pos--;

                JOptionPane.showMessageDialog(null, "L'Employee supprimé avec succeé!!");

            }
        } catch (Exception ex) {
            Logger.getLogger(SupprimerEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnmodifieretudActionPerformed

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        try {
            Employee e = (Employee) combo.getSelectedItem();
            txtnom.setText(e.getNom());
            txtprenom.setText(e.getPrenom());
            txtid.setText(e.getIdemp() + "");

        } catch (Exception ex) {
            Logger.getLogger(SupprimerEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboItemStateChanged

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        pos = 0;
        Afficher();
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreActionPerformed
        // TODO add your handling code here:
        try {
            pos--;
            Afficher();
        } catch (IndexOutOfBoundsException e) {
            pos++;
            JOptionPane.showMessageDialog(rootPane, "le dernier");
        }
    }//GEN-LAST:event_btnpreActionPerformed

    private void btnsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivActionPerformed
        // TODO add your handling code here:
        try {
            pos++;
            Afficher();
        } catch (IndexOutOfBoundsException e) {
            pos--;
            JOptionPane.showMessageDialog(rootPane, "le dernier");
        }
    }//GEN-LAST:event_btnsuivActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
        pos = le.size() - 1;
        Afficher();
    }//GEN-LAST:event_btndernierActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = UtilConnexion.seConnecter();
            Statement s = con.createStatement();

            ResultSet r = s.executeQuery("select * from employee");
            while (r.next()) {

                combo.addItem(new Employee(r.getInt("idemp"), r.getString("nom"), r.getString("prenom"),
                        r.getString("adresse"), r.getString("tel"), r.getString("email"), r.getString("departement"),
                        r.getInt("salary"), r.getInt("rib")));
            }
            s.close();
            r.close();

            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("select * from employee");
            while (rs2.next()) {
                le.add(new Employee(rs2.getInt("idemp"), rs2.getString("nom"), rs2.getString("prenom"),
                        rs2.getString("adresse"), rs2.getString("tel"), rs2.getString("email"), rs2.getString("departement"),
                        rs2.getInt("salary"), rs2.getInt("rib")));
            }
            Afficher();
            st2.close();
            rs2.close();
            con.close();

        } catch (Exception ex) {
            Logger.getLogger(SupprimerEmp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formInternalFrameOpened
    private void Afficher() {
        Employee e = le.get(pos);
        txtid.setText(e.getIdemp() + "");
        txtnom.setText(e.getNom());
        txtprenom.setText(e.getPrenom());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnmodifieretud;
    private javax.swing.JButton btnpre;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuiv;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
