/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Client;
import models.Location;
import pfe.UtilConnexion;

/**
 *
 * @author mehdierror404
 */
public class SupprimerClt extends javax.swing.JInternalFrame {

    /**
     * Creates new form SupprimerEtud
     */
    Connection con;

    int pos = 0;
    ArrayList<Client> le = new ArrayList<Client>();

    public SupprimerClt() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        btnsuppetud = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnpremier = new javax.swing.JButton();
        btnpre = new javax.swing.JButton();
        btnsuiv = new javax.swing.JButton();
        btndernier = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(1370, 658));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(120, 196, 212));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(1370, 700));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Selectionner un client pour Supprimer");

        combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1)))
                .addContainerGap(386, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 180));

        jPanel2.setBackground(new java.awt.Color(120, 196, 212));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setPreferredSize(new java.awt.Dimension(1370, 700));

        txtnom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtnom.setEnabled(false);

        jLabel2.setText("Nom:");

        jLabel13.setText("Prènom:");

        txtprenom.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtprenom.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtprenom.setEnabled(false);

        btnsuppetud.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        btnsuppetud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_24px_1.png"))); // NOI18N
        btnsuppetud.setText("Supprimer client");
        btnsuppetud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuppetud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuppetudActionPerformed(evt);
            }
        });

        txtid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        txtid.setEnabled(false);

        jLabel3.setText("ID-Client:");

        btnpremier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_skip_to_start_26px.png"))); // NOI18N
        btnpremier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpremierActionPerformed(evt);
            }
        });

        btnpre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_back_26px.png"))); // NOI18N
        btnpre.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreActionPerformed(evt);
            }
        });

        btnsuiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_next_page_26px.png"))); // NOI18N
        btnsuiv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuivActionPerformed(evt);
            }
        });

        btndernier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_end_26px.png"))); // NOI18N
        btndernier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btndernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndernierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnpremier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnpre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btndernier, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnsuppetud)
                        .addGap(158, 158, 158)))
                .addContainerGap(431, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel13))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpremier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsuiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndernier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnsuppetud)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1350, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsuppetudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuppetudActionPerformed
        try {
            // TODO add your handling code here:
            Client c = le.get(pos);
            if (JOptionPane.showConfirmDialog(null, "Voulez vraiment Supprimer cet Client?") == JOptionPane.YES_OPTION) {
                con = UtilConnexion.seConnecter();
                PreparedStatement ps = con.prepareStatement("delete from client where idclt=?");
                ps.setInt(1, Integer.parseInt(txtid.getText()));
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Client supprimé avec succeé!!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erreur;" + ex);

        }


    }//GEN-LAST:event_btnsuppetudActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection con = UtilConnexion.seConnecter();
            Statement st = con.createStatement();
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery("select * from client join location using(id_loc)");
            while (r.next()) {

                combo.addItem(new Client(r.getInt("idclt"), r.getString("nom"), r.getString("prenom"), r.getDate("date_rend"), r.getString("email"), r.getString("tel"), r.getInt("prix_ser"), r.getInt("VERSEMENT"),
                        (new Location(r.getInt("id_loc"), r.getString("rue_Adresse"), r.getString("ville"), r.getInt("code_postal")))));
            }
            s.close();
            r.close();

            Statement st2 = con.createStatement();
            ResultSet rs2 = st.executeQuery("select * from client  join location using(id_loc)");
            while (rs2.next()) {
                le.add(new Client(rs2.getInt("idclt"), rs2.getString("nom"), rs2.getString("prenom"), rs2.getDate("date_rend"), rs2.getString("email"), rs2.getString("tel"), rs2.getInt("prix_ser"), rs2.getInt("VERSEMENT"),
                        (new Location(rs2.getInt("id_loc"), rs2.getString("rue_Adresse"), rs2.getString("ville"), rs2.getInt("code_postal")))));
            }
            Afficher();
            st2.close();
            rs2.close();
            con.close();

        } catch (Exception ex) {
            Logger.getLogger(ModifierLoc.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_formInternalFrameOpened

    private void comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboItemStateChanged
        // TODO add your handling code here:
        try {
            Client e = (Client) combo.getSelectedItem();
            txtnom.setText(e.getNom());
            txtprenom.setText(e.getPrenom());
            txtid.setText(e.getIdclt() + "");

        } catch (Exception ex) {
            Logger.getLogger(SupprimerClt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_comboItemStateChanged

    private void btnpremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpremierActionPerformed
        // TODO add your handling code here:
        pos = 0;
        Afficher();
    }//GEN-LAST:event_btnpremierActionPerformed

    private void btnpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreActionPerformed
        // TODO add your handling code here:
        try {
            pos--;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos++;
            JOptionPane.showMessageDialog(rootPane, "Le premier");
            Afficher();
        }

    }//GEN-LAST:event_btnpreActionPerformed

    private void btnsuivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuivActionPerformed
        // TODO add your handling code here:
        try {
            pos++;
            Afficher();
        } catch (IndexOutOfBoundsException ex) {
            pos--;
            JOptionPane.showMessageDialog(rootPane, "Le dernier");
            Afficher();
        }
    }//GEN-LAST:event_btnsuivActionPerformed

    private void btndernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndernierActionPerformed
        // TODO add your handling code here:
        pos = le.size() - 1;
        Afficher();
    }//GEN-LAST:event_btndernierActionPerformed
    private void Afficher() {
        Client e = le.get(pos);
        txtid.setText(e.getIdclt() + "");
        txtnom.setText(e.getNom());
        txtprenom.setText(e.getPrenom());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndernier;
    private javax.swing.JButton btnpre;
    private javax.swing.JButton btnpremier;
    private javax.swing.JButton btnsuiv;
    private javax.swing.JButton btnsuppetud;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
